version: '2'

services:
  nginx:
    image: nginx:stable-alpine
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8000:80"

  tarantool1:
    build: .
    environment:
      TARANTOOL_REPLICATION_SOURCE: "tarantool1,tarantool2,tarantool3"

  tarantool2:
    build: .
    environment:
      TARANTOOL_REPLICATION_SOURCE: "tarantool1,tarantool2,tarantool3"

  tarantool3:
    build: .
    environment:
      TARANTOOL_REPLICATION_SOURCE: "tarantool1,tarantool2,tarantool3"
